Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = Application.SldWorks
Set Part = swApp.ActiveDoc
Proc1
Proc2
Proc3
Proc4
Proc5
Proc6
Proc7
Proc8
Proc9
Proc10
Proc11
Proc12
Proc13
Proc14
Proc15
Proc16
Proc17
Proc18
Proc19
Proc20
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.00231262, -0.00182843, 0.02095500, False, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.00211680, -0.00236411, 0.02720474, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.00223617, -0.00271440, 0.03345447, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.00249537, -0.00287881, 0.03970421, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.00282783, -0.00287835, 0.04595395, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.00351723, -0.00287119, 0.05220368, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.00552270, -0.00325720, 0.05845342, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.00756485, -0.00349210, 0.06470316, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.00948977, -0.00359409, 0.07095289, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.01123743, -0.00358632, 0.07720263, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.01275123, -0.00349398, 0.08345237, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.01289014, -0.00310294, 0.08970211, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve13", "REFERENCECURVES", -0.01208902, -0.00258381, 0.09595184, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve14", "REFERENCECURVES", -0.01103539, -0.00209482, 0.10220158, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve15", "REFERENCECURVES", -0.00978747, -0.00163788, 0.10845132, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve16", "REFERENCECURVES", -0.00828882, -0.00121351, 0.11470105, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve17", "REFERENCECURVES", -0.00686848, -0.00083556, 0.12095079, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve18", "REFERENCECURVES", -0.00678812, -0.00066149, 0.12720053, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve19", "REFERENCECURVES", -0.00585563, -0.00585251, 0.13245522, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Curve20", "REFERENCECURVES", -0.00522598, -0.01340759, 0.13263761, True, 1, Nothing, 0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub

Sub Proc1()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00231262, -0.00182843, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00232201, -0.00179355, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00234920, -0.00169261, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00193825, -0.00141403, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00117400, -0.00099736, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00022623, -0.00050828, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00087785, 0.00002491, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00210496, 0.00057278, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00341658, 0.00110609, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00477003, 0.00159708, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00612951, 0.00202043, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00745767, 0.00233337, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00869064, 0.00252003, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00977735, 0.00258580, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01067256, 0.00254594, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01134017, 0.00242162, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01175535, 0.00223452, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01190555, 0.00200133, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01190555, 0.00200133, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01178923, 0.00175006, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01141567, 0.00150298, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.01080407, 0.00126068, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00998055, 0.00102135, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00897647, 0.00077979, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00782706, 0.00052740, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00657067, 0.00025367, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00523448, -0.00004854, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00386212, -0.00035713, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00250910, -0.00066457, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00122199, -0.00096449, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(0.00004512, -0.00124691, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00098083, -0.00149976, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00181994, -0.00171086, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00231106, -0.00183422, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00231224, -0.00182982, 0.02095500)
boolstatus = Part.InsertCurveFilePoint(-0.00231262, -0.00182843, 0.02095500)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
End Sub

Sub Proc2()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00211680, -0.00236411, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00213034, -0.00232574, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00216954, -0.00221468, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00223031, -0.00204246, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00167844, -0.00160452, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00065574, -0.00097391, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00053875, -0.00028036, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00187018, 0.00044021, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00329779, 0.00115170, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00477601, 0.00181922, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00626681, 0.00241128, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00773188, 0.00287663, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00910086, 0.00319197, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01031590, 0.00335898, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01132489, 0.00339094, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01208546, 0.00330851, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01256786, 0.00313392, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01275656, 0.00288487, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01275656, 0.00288487, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01264744, 0.00259265, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01224900, 0.00228309, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01158277, 0.00195851, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.01067824, 0.00161909, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00957108, 0.00126169, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00830160, 0.00087967, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00691378, 0.00046452, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00543877, 0.00001052, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00392367, -0.00045373, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00243020, -0.00091504, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(0.00101012, -0.00136224, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00028764, -0.00178035, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00141839, -0.00215231, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00211132, -0.00237963, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00211455, -0.00237048, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00211626, -0.00236563, 0.02720474)
boolstatus = Part.InsertCurveFilePoint(-0.00211680, -0.00236411, 0.02720474)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
End Sub

Sub Proc3()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00223617, -0.00271440, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00225319, -0.00267164, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00230245, -0.00254790, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00237885, -0.00235600, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00242067, -0.00209353, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00129323, -0.00133511, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00002553, -0.00049789, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00149783, 0.00037602, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00307921, 0.00124394, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00471976, 0.00206446, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00637790, 0.00280027, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00801265, 0.00339175, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00954552, 0.00380940, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01091108, 0.00405254, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01204984, 0.00413383, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01291301, 0.00407475, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01346596, 0.00389906, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01369034, 0.00362607, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01369034, 0.00362607, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01358012, 0.00329097, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01314374, 0.00292331, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01240540, 0.00252668, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01139845, 0.00210262, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.01016333, 0.00164917, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00874588, 0.00116063, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00719619, 0.00062934, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00554970, 0.00005026, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00385837, -0.00054221, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00219135, -0.00113039, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(0.00060664, -0.00169934, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00084115, -0.00222993, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00210228, -0.00270089, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00222928, -0.00273169, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00223334, -0.00272149, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00223549, -0.00271609, 0.03345447)
boolstatus = Part.InsertCurveFilePoint(-0.00223617, -0.00271440, 0.03345447)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
End Sub

Sub Proc4()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00249537, -0.00287881, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00251491, -0.00283148, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00257147, -0.00269453, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00265918, -0.00248214, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00276931, -0.00221547, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00204149, -0.00156870, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00058633, -0.00061860, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00103911, 0.00037449, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00278599, 0.00136247, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00459936, 0.00229856, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00643350, 0.00314066, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00824367, 0.00382187, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00994298, 0.00430826, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01145863, 0.00459814, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01272429, 0.00470475, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01368536, 0.00465128, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01430298, 0.00446369, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01455647, 0.00416319, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01455647, 0.00416319, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01443861, 0.00378885, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01395838, 0.00337365, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01314266, 0.00292193, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01202851, 0.00243588, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.01066093, 0.00191389, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00909104, 0.00135028, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00737464, 0.00073724, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00555123, 0.00006965, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00367814, -0.00061346, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00183202, -0.00129146, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(0.00007719, -0.00194690, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00152586, -0.00255771, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00247967, -0.00291683, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00248746, -0.00289795, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00249212, -0.00288666, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00249459, -0.00288068, 0.03970421)
boolstatus = Part.InsertCurveFilePoint(-0.00249537, -0.00287881, 0.03970421)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
End Sub

Sub Proc5()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00282783, -0.00287835, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00284887, -0.00282652, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00290977, -0.00267651, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00300421, -0.00244388, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00312279, -0.00215179, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00286844, -0.00167120, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00127228, -0.00064266, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00051021, 0.00043172, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00242535, 0.00149974, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00441280, 0.00251062, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00642232, 0.00341867, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00840461, 0.00415107, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01026448, 0.00467136, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01192240, 0.00497813, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01330597, 0.00508630, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01435569, 0.00502158, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01502928, 0.00481257, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01530427, 0.00448257, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01530427, 0.00448257, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01517305, 0.00407433, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01464562, 0.00362383, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01375138, 0.00313563, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01253086, 0.00261189, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.01103321, 0.00205053, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00931422, 0.00144504, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00743484, 0.00078648, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00543819, 0.00006904, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00338714, -0.00066504, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(0.00136561, -0.00139371, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00055603, -0.00209833, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00231155, -0.00275519, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00281092, -0.00292000, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00281932, -0.00289932, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00282434, -0.00288696, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00282699, -0.00288041, 0.04595395)
boolstatus = Part.InsertCurveFilePoint(-0.00282783, -0.00287835, 0.04595395)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
End Sub

Sub Proc6()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00351723, -0.00287119, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00353886, -0.00281499, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00360146, -0.00265234, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00369854, -0.00240010, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00382044, -0.00208340, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00376502, -0.00165880, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00202689, -0.00058309, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00008731, 0.00053829, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00199492, 0.00165023, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00415386, 0.00269924, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00633454, 0.00363714, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00848245, 0.00438654, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01049444, 0.00491003, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01228488, 0.00520768, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01377615, 0.00529696, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01490470, 0.00520669, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01562558, 0.00496851, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01591509, 0.00460794, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01591509, 0.00460794, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01576584, 0.00417113, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01518932, 0.00369660, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01421728, 0.00318870, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01289334, 0.00264894, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.01127040, 0.00207414, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00940837, 0.00145617, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00737267, 0.00078424, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00520959, 0.00005124, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00298763, -0.00069861, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(0.00079755, -0.00144321, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00128455, -0.00216389, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00318691, -0.00283642, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00349985, -0.00291635, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00350848, -0.00289393, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00351364, -0.00288052, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00351637, -0.00287342, 0.05220368)
boolstatus = Part.InsertCurveFilePoint(-0.00351723, -0.00287119, 0.05220368)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
End Sub

Sub Proc7()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00552270, -0.00325720, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00554419, -0.00319686, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00560637, -0.00302225, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00570281, -0.00275147, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00582390, -0.00241147, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00461634, -0.00155651, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00273947, -0.00045954, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00064719, 0.00068060, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00159650, 0.00180684, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00392005, 0.00286413, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00626373, 0.00380271, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00856751, 0.00454175, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01072071, 0.00504425, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01263229, 0.00531260, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01422020, 0.00536745, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01541764, 0.00524116, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01617767, 0.00496856, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01647578, 0.00457743, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01647578, 0.00457743, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01630536, 0.00411702, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01567967, 0.00362800, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01463255, 0.00311412, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01321045, 0.00257582, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.01146951, 0.00200831, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00947320, 0.00140132, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00729080, 0.00074164, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00497134, 0.00002044, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00258883, -0.00071710, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(0.00024034, -0.00144990, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00199269, -0.00216017, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00403334, -0.00282409, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00550543, -0.00330568, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00551401, -0.00328160, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00551913, -0.00326721, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00552185, -0.00325959, 0.05845342)
boolstatus = Part.InsertCurveFilePoint(-0.00552270, -0.00325720, 0.05845342)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
End Sub

Sub Proc8()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00756485, -0.00349210, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00758564, -0.00342802, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00764581, -0.00324260, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00773911, -0.00295505, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00723055, -0.00239096, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00551163, -0.00139060, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00350576, -0.00029334, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00127216, 0.00084287, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00112020, 0.00195997, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00359447, 0.00300218, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00608636, 0.00391900, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00853035, 0.00462723, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01080898, 0.00509130, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01282662, 0.00531640, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01449761, 0.00532670, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01575270, 0.00515822, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01654359, 0.00484896, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01684532, 0.00442887, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01684532, 0.00442887, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01665243, 0.00394993, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01598005, 0.00345449, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01486390, 0.00294549, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01335280, 0.00242200, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.01150563, 0.00187730, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00938883, 0.00129872, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00707481, 0.00067029, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00461487, -0.00001873, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(0.00208815, -0.00072303, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00040265, -0.00142338, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00277141, -0.00210348, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00493653, -0.00274059, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00682334, -0.00330838, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00755644, -0.00351801, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00756140, -0.00350273, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00756402, -0.00349464, 0.06470316)
boolstatus = Part.InsertCurveFilePoint(-0.00756485, -0.00349210, 0.06470316)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
End Sub

Sub Proc9()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00948977, -0.00359409, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00950946, -0.00352691, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00956645, -0.00333251, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00959482, -0.00301346, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00813199, -0.00217358, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00631671, -0.00118556, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00420048, -0.00010542, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00184653, 0.00100841, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00067176, 0.00209767, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00327291, 0.00310671, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00588863, 0.00398496, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00844839, 0.00464798, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01082913, 0.00506227, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01293165, 0.00523610, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01466771, 0.00519712, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01596643, 0.00498479, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01677878, 0.00464004, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01707971, 0.00419469, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01707971, 0.00419469, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01686510, 0.00370293, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01615194, 0.00320828, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01497739, 0.00271273, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01339217, 0.00221388, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.01145722, 0.00170300, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00924118, 0.00116494, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00681880, 0.00058095, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00424303, -0.00006162, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(0.00159745, -0.00071809, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00101071, -0.00137152, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00349149, -0.00200754, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00575946, -0.00260496, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00773628, -0.00313866, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00935293, -0.00358348, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00948650, -0.00360524, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00948899, -0.00359675, 0.07095289)
boolstatus = Part.InsertCurveFilePoint(-0.00948977, -0.00359409, 0.07095289)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
End Sub

Sub Proc10()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01123743, -0.00358632, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01125575, -0.00351695, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01130875, -0.00331622, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01040744, -0.00274522, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00888552, -0.00192523, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00699843, -0.00096322, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00480046, 0.00008485, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00235801, 0.00116085, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00025212, 0.00220713, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00294493, 0.00316894, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00564904, 0.00399635, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00828987, 0.00460480, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01074041, 0.00496338, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01289926, 0.00508331, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01467678, 0.00499534, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01600146, 0.00474188, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01682417, 0.00436620, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01712016, 0.00390162, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01712016, 0.00390162, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01688669, 0.00340374, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01614237, 0.00291670, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01492533, 0.00244151, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01328745, 0.00197429, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.01129096, 0.00150442, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00900573, 0.00101448, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00650783, 0.00048320, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00385117, -0.00010387, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(0.00112260, -0.00070323, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00156755, -0.00130052, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00412672, -0.00188350, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00646679, -0.00243282, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.00850682, -0.00292491, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01017539, -0.00333589, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01123439, -0.00359783, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01123670, -0.00358907, 0.07720263)
boolstatus = Part.InsertCurveFilePoint(-0.01123743, -0.00358632, 0.07720263)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
End Sub

Sub Proc11()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01275123, -0.00349398, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01276800, -0.00342359, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01214780, -0.00306059, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01100772, -0.00245520, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00945294, -0.00166571, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00752645, -0.00074196, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00528438, 0.00026092, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00279509, 0.00128598, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00013744, 0.00227695, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00260149, 0.00318070, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00534853, 0.00394867, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00802638, 0.00449739, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01050622, 0.00479882, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01268608, 0.00486676, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01447630, 0.00473443, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01580584, 0.00444634, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01662621, 0.00404733, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01691327, 0.00357160, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01691327, 0.00357160, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01666563, 0.00307529, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01590313, 0.00260244, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01466424, 0.00215314, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01300121, 0.00172222, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.01097648, 0.00129741, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00866011, 0.00085946, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00612828, 0.00038505, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00343498, -0.00014172, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(0.00066888, -0.00067913, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00205843, -0.00121538, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00465331, -0.00174043, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00702644, -0.00223691, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.00909561, -0.00268304, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01078823, -0.00305651, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01204376, -0.00333782, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01275057, -0.00349677, 0.08345237)
boolstatus = Part.InsertCurveFilePoint(-0.01275123, -0.00349398, 0.08345237)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
End Sub

Sub Proc12()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01289014, -0.00310294, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01290527, -0.00303284, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01251079, -0.00273539, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01136828, -0.00215961, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00981096, -0.00141017, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00788246, -0.00053555, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00563959, 0.00041081, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00315127, 0.00137392, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00049685, 0.00229969, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00223627, 0.00313732, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00497456, 0.00384023, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00763965, 0.00432734, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01010331, 0.00457361, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01226477, 0.00459485, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01403591, 0.00442588, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01534726, 0.00411230, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01615174, 0.00369958, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01642613, 0.00322211, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01642613, 0.00322211, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01617025, 0.00273554, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01540469, 0.00228311, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01416758, 0.00186410, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01251055, 0.00147225, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.01049526, 0.00109411, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00819071, 0.00070912, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00567188, 0.00029254, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00299195, -0.00017250, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(0.00023964, -0.00064654, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00247419, -0.00112026, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00505657, -0.00158568, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00741860, -0.00202747, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.00947838, -0.00242580, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01116350, -0.00276009, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01241356, -0.00301230, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01288955, -0.00310572, 0.08970211)
boolstatus = Part.InsertCurveFilePoint(-0.01289014, -0.00310294, 0.08970211)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
End Sub

Sub Proc13()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01208902, -0.00258381, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01210248, -0.00251530, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01214141, -0.00231706, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01148883, -0.00186959, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00995972, -0.00116835, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00806712, -0.00035198, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00586728, 0.00052853, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00342827, 0.00142091, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00082828, 0.00227395, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00184671, 0.00303980, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00452430, 0.00367444, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00712676, 0.00410039, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00952883, 0.00429559, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01163274, 0.00427724, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01335336, 0.00408083, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01462390, 0.00375198, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01539937, 0.00333580, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01565779, 0.00286617, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01565779, 0.00286617, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01539998, 0.00239727, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01464677, 0.00197078, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01343526, 0.00158533, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.01181557, 0.00123389, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00984747, 0.00090227, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00759773, 0.00056919, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00513889, 0.00020925, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(0.00252239, -0.00019495, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00016471, -0.00060661, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00281436, -0.00101865, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00533592, -0.00142497, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00764263, -0.00181229, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.00965439, -0.00216276, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01130038, -0.00245768, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01208679, -0.00259518, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01208849, -0.00258652, 0.09595184)
boolstatus = Part.InsertCurveFilePoint(-0.01208902, -0.00258381, 0.09595184)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve13")
End Sub

Sub Proc14()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01103539, -0.00209482, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01104719, -0.00202909, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01108132, -0.00183885, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01113426, -0.00154385, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00992486, -0.00094450, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00810175, -0.00019335, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00598375, 0.00061435, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00363679, 0.00142965, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00113647, 0.00220479, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00143422, 0.00289536, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00400533, 0.00346037, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00650130, 0.00382696, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00880198, 0.00397597, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01081412, 0.00392540, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01245684, 0.00371052, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01366697, 0.00337604, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01440219, 0.00296578, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01464200, 0.00251252, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01464200, 0.00251252, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01438804, 0.00206805, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01366089, 0.00167194, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01249601, 0.00132225, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.01094124, 0.00101152, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00905351, 0.00072521, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00689637, 0.00044192, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00453881, 0.00013622, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(0.00202974, -0.00020934, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00054697, -0.00056092, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00308787, -0.00091346, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00550616, -0.00126254, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00771863, -0.00159681, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.00964842, -0.00190047, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01103062, -0.00212141, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01103344, -0.00210573, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01103493, -0.00209743, 0.10220158)
boolstatus = Part.InsertCurveFilePoint(-0.01103539, -0.00209482, 0.10220158)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve14")
End Sub

Sub Proc15()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00978747, -0.00163788, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00979764, -0.00157581, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00982706, -0.00139617, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00987268, -0.00111759, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00974910, -0.00073819, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00802146, -0.00005690, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00601529, 0.00067341, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00379341, 0.00140759, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00142767, 0.00210176, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00100313, 0.00271527, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00343252, 0.00321055, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00578832, 0.00352003, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00795708, 0.00362741, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00985126, 0.00355098, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01139519, 0.00332509, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01253002, 0.00299276, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01321652, 0.00259588, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01343587, 0.00216560, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01343587, 0.00216560, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01319034, 0.00175066, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01249989, 0.00138804, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.01139787, 0.00107542, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00992924, 0.00080505, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00814740, 0.00056246, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00611189, 0.00032657, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00388731, 0.00007244, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(0.00151949, -0.00021705, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00091212, -0.00051125, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00331002, -0.00080686, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00559241, -0.00110097, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00768076, -0.00138408, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00950245, -0.00164241, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00978336, -0.00166298, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00978578, -0.00164818, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00978707, -0.00164034, 0.10845132)
boolstatus = Part.InsertCurveFilePoint(-0.00978747, -0.00163788, 0.10845132)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve15")
End Sub

Sub Proc16()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00828882, -0.00121351, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00829739, -0.00115576, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00832217, -0.00098863, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00836061, -0.00072944, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00840888, -0.00040401, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00774982, 0.00006260, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00587767, 0.00071228, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00380526, 0.00136252, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00159991, 0.00197363, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00066470, 0.00250896, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00292634, 0.00293457, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00511708, 0.00318878, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00713140, 0.00325804, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00888830, 0.00316056, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01031805, 0.00292928, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01136662, 0.00260494, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01199820, 0.00222698, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01219574, 0.00182456, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01219574, 0.00182456, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01196206, 0.00144290, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01131617, 0.00111603, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.01028901, 0.00084133, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00892219, 0.00061099, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00726508, 0.00041081, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00537263, 0.00022041, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00330445, 0.00001574, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(0.00110283, -0.00021976, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00115805, -0.00045872, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00338767, -0.00069946, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00551006, -0.00094044, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00745222, -0.00117392, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00828194, -0.00125992, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00828536, -0.00123687, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00828740, -0.00122310, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00828848, -0.00121580, 0.11470105)
boolstatus = Part.InsertCurveFilePoint(-0.00828882, -0.00121351, 0.11470105)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve16")
End Sub

Sub Proc17()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00686848, -0.00083556, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00687543, -0.00078285, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00689555, -0.00063031, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00692674, -0.00039375, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00696592, -0.00009673, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00700936, 0.00023268, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00577702, 0.00073321, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00388053, 0.00129486, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00186356, 0.00181892, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00020625, 0.00227312, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00227176, 0.00262747, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00427018, 0.00282679, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00610527, 0.00286030, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00770352, 0.00274576, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00900193, 0.00251420, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00995191, 0.00220351, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.01052142, 0.00185010, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.01069539, 0.00148079, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.01069539, 0.00148079, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.01047701, 0.00113672, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00988412, 0.00084857, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00894485, 0.00061352, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00769697, 0.00042385, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00618521, 0.00026590, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00445931, 0.00012030, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00257320, -0.00003572, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(0.00056515, -0.00021783, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00149693, -0.00040224, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00353056, -0.00058873, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00546656, -0.00077700, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00685853, -0.00091101, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00686289, -0.00087791, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00686567, -0.00085688, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00686732, -0.00084431, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00686820, -0.00083765, 0.12095079)
boolstatus = Part.InsertCurveFilePoint(-0.00686848, -0.00083556, 0.12095079)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve17")
End Sub

Sub Proc18()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00678812, -0.00066149, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00679336, -0.00061530, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00680853, -0.00048164, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00683205, -0.00027437, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00686158, -0.00001412, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00689433, 0.00027451, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00553148, 0.00072402, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00386482, 0.00118491, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00209345, 0.00161104, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00027700, 0.00197526, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00153410, 0.00225227, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00328412, 0.00239483, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00488872, 0.00239504, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00628396, 0.00226959, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00741525, 0.00204660, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00824072, 0.00175996, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00873294, 0.00144202, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00887916, 0.00111644, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00887916, 0.00111644, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00868282, 0.00081914, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00816000, 0.00057667, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00733524, 0.00038609, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00624144, 0.00024007, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00491749, 0.00012596, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00340655, 0.00002604, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(0.00175540, -0.00008044, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00000276, -0.00020781, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00180817, -0.00033633, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00358876, -0.00046711, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00528403, -0.00060100, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00678062, -0.00072759, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00678391, -0.00069860, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00678600, -0.00068017, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00678725, -0.00066915, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00678791, -0.00066332, 0.12720053)
boolstatus = Part.InsertCurveFilePoint(-0.00678812, -0.00066149, 0.12720053)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve18")
End Sub

Sub Proc19()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00585563, -0.00585251, 0.13245522)
boolstatus = Part.InsertCurveFilePoint(-0.00585897, -0.00582696, 0.13248078)
boolstatus = Part.InsertCurveFilePoint(-0.00586863, -0.00575300, 0.13255473)
boolstatus = Part.InsertCurveFilePoint(-0.00588361, -0.00563831, 0.13266942)
boolstatus = Part.InsertCurveFilePoint(-0.00590242, -0.00549431, 0.13281342)
boolstatus = Part.InsertCurveFilePoint(-0.00592328, -0.00533461, 0.13297313)
boolstatus = Part.InsertCurveFilePoint(-0.00483640, -0.00510118, 0.13320655)
boolstatus = Part.InsertCurveFilePoint(-0.00352780, -0.00486600, 0.13344174)
boolstatus = Part.InsertCurveFilePoint(-0.00213801, -0.00465121, 0.13365652)
boolstatus = Part.InsertCurveFilePoint(-0.00071405, -0.00447112, 0.13383662)
boolstatus = Part.InsertCurveFilePoint(0.00070432, -0.00433911, 0.13396863)
boolstatus = Part.InsertCurveFilePoint(0.00207280, -0.00428060, 0.13402713)
boolstatus = Part.InsertCurveFilePoint(0.00332545, -0.00429900, 0.13400873)
boolstatus = Part.InsertCurveFilePoint(0.00441260, -0.00438435, 0.13392338)
boolstatus = Part.InsertCurveFilePoint(0.00529211, -0.00452049, 0.13378724)
boolstatus = Part.InsertCurveFilePoint(0.00593184, -0.00468824, 0.13361949)
boolstatus = Part.InsertCurveFilePoint(0.00631091, -0.00486943, 0.13343830)
boolstatus = Part.InsertCurveFilePoint(0.00641973, -0.00505084, 0.13325690)
boolstatus = Part.InsertCurveFilePoint(0.00641973, -0.00505084, 0.13325690)
boolstatus = Part.InsertCurveFilePoint(0.00626161, -0.00521268, 0.13309505)
boolstatus = Part.InsertCurveFilePoint(0.00584951, -0.00534050, 0.13296723)
boolstatus = Part.InsertCurveFilePoint(0.00520255, -0.00543618, 0.13287155)
boolstatus = Part.InsertCurveFilePoint(0.00434629, -0.00550416, 0.13280357)
boolstatus = Part.InsertCurveFilePoint(0.00331088, -0.00555188, 0.13275585)
boolstatus = Part.InsertCurveFilePoint(0.00212972, -0.00558960, 0.13271813)
boolstatus = Part.InsertCurveFilePoint(0.00083901, -0.00562933, 0.13267840)
boolstatus = Part.InsertCurveFilePoint(-0.00053559, -0.00567935, 0.13262838)
boolstatus = Part.InsertCurveFilePoint(-0.00194709, -0.00572946, 0.13257827)
boolstatus = Part.InsertCurveFilePoint(-0.00333924, -0.00578111, 0.13252662)
boolstatus = Part.InsertCurveFilePoint(-0.00466485, -0.00583546, 0.13247228)
boolstatus = Part.InsertCurveFilePoint(-0.00585085, -0.00588909, 0.13241865)
boolstatus = Part.InsertCurveFilePoint(-0.00585295, -0.00587304, 0.13243469)
boolstatus = Part.InsertCurveFilePoint(-0.00585428, -0.00586285, 0.13244489)
boolstatus = Part.InsertCurveFilePoint(-0.00585508, -0.00585675, 0.13245098)
boolstatus = Part.InsertCurveFilePoint(-0.00585550, -0.00585352, 0.13245421)
boolstatus = Part.InsertCurveFilePoint(-0.00585563, -0.00585251, 0.13245522)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve19")
End Sub

Sub Proc20()
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00522598, -0.01340759, 0.13263761)
boolstatus = Part.InsertCurveFilePoint(-0.00522724, -0.01340759, 0.13265610)
boolstatus = Part.InsertCurveFilePoint(-0.00523089, -0.01340759, 0.13270962)
boolstatus = Part.InsertCurveFilePoint(-0.00523654, -0.01340759, 0.13279261)
boolstatus = Part.InsertCurveFilePoint(-0.00524364, -0.01340759, 0.13289681)
boolstatus = Part.InsertCurveFilePoint(-0.00525152, -0.01340759, 0.13301238)
boolstatus = Part.InsertCurveFilePoint(-0.00525946, -0.01340759, 0.13312893)
boolstatus = Part.InsertCurveFilePoint(-0.00465279, -0.01340759, 0.13327821)
boolstatus = Part.InsertCurveFilePoint(-0.00393952, -0.01340759, 0.13341622)
boolstatus = Part.InsertCurveFilePoint(-0.00320939, -0.01340759, 0.13352877)
boolstatus = Part.InsertCurveFilePoint(-0.00248296, -0.01340759, 0.13360667)
boolstatus = Part.InsertCurveFilePoint(-0.00178327, -0.01340759, 0.13363211)
boolstatus = Part.InsertCurveFilePoint(-0.00114406, -0.01340759, 0.13360345)
boolstatus = Part.InsertCurveFilePoint(-0.00059050, -0.01340759, 0.13352848)
boolstatus = Part.InsertCurveFilePoint(-0.00014384, -0.01340759, 0.13341938)
boolstatus = Part.InsertCurveFilePoint(0.00017986, -0.01340759, 0.13329040)
boolstatus = Part.InsertCurveFilePoint(0.00037024, -0.01340759, 0.13315493)
boolstatus = Part.InsertCurveFilePoint(0.00042266, -0.01340759, 0.13302262)
boolstatus = Part.InsertCurveFilePoint(0.00042266, -0.01340759, 0.13302262)
boolstatus = Part.InsertCurveFilePoint(0.00033912, -0.01340759, 0.13290770)
boolstatus = Part.InsertCurveFilePoint(0.00012650, -0.01340759, 0.13282048)
boolstatus = Part.InsertCurveFilePoint(-0.00020546, -0.01340759, 0.13275933)
boolstatus = Part.InsertCurveFilePoint(-0.00064380, -0.01340759, 0.13272076)
boolstatus = Part.InsertCurveFilePoint(-0.00117325, -0.01340759, 0.13269902)
boolstatus = Part.InsertCurveFilePoint(-0.00177694, -0.01340759, 0.13268629)
boolstatus = Part.InsertCurveFilePoint(-0.00243660, -0.01340759, 0.13267345)
boolstatus = Part.InsertCurveFilePoint(-0.00313926, -0.01340759, 0.13265421)
boolstatus = Part.InsertCurveFilePoint(-0.00386076, -0.01340759, 0.13263536)
boolstatus = Part.InsertCurveFilePoint(-0.00457242, -0.01340759, 0.13261517)
boolstatus = Part.InsertCurveFilePoint(-0.00522301, -0.01340759, 0.13259405)
boolstatus = Part.InsertCurveFilePoint(-0.00522417, -0.01340759, 0.13261114)
boolstatus = Part.InsertCurveFilePoint(-0.00522496, -0.01340759, 0.13262275)
boolstatus = Part.InsertCurveFilePoint(-0.00522547, -0.01340759, 0.13263013)
boolstatus = Part.InsertCurveFilePoint(-0.00522577, -0.01340759, 0.13263454)
boolstatus = Part.InsertCurveFilePoint(-0.00522593, -0.01340759, 0.13263688)
boolstatus = Part.InsertCurveFilePoint(-0.00522598, -0.01340759, 0.13263761)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve20")
End Sub

